run:
	python3 manage.py runserver 8000

install:
	pip3 install -r requirements.txt

backend:
	python3 manage.py runserver 8080

migrate:
	python3 manage.py migrate

collectstatic:
	python3 manage.py collectstatic --noinput

all: install run